//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyVersion("0.1.7")]
[assembly: AssemblyFileVersion("0.1.7")]

// Generated by the MSBuild WriteCodeFragment class on 2016-04-29 22:53:11.

